// AUTOMATICALLY GENERATED. DO NOT MODIFY.

using System.Runtime.InteropServices;
using System.Text;

namespace LibPff.Interop
{
    public interface INativeAdapter
    {
        int AttachmentGetType(IntPtr attachment, out int attachment_type, IntPtr error);
        int AttachmentGetDataSize(IntPtr attachment, out long size, IntPtr error);
        long AttachmentDataReadBuffer(IntPtr attachment, byte[] buffer, UIntPtr buffer_size, IntPtr error);
        long AttachmentDataSeekOffset(IntPtr attachment, long offset, int whence, IntPtr error);
        int AttachmentGetDataFileIoHandle(IntPtr attachment, out IntPtr file_io_handle, IntPtr error);
        int AttachmentGetItem(IntPtr attachment, out IntPtr attached_item, IntPtr error);
        void ErrorFree(out IntPtr error);
        int ErrorFprint(IntPtr error, IntPtr stream);
        int ErrorSprint(IntPtr error, StringBuilder string_2, UIntPtr size);
        int ErrorBacktraceFprint(IntPtr error, IntPtr stream);
        int ErrorBacktraceSprint(IntPtr error, StringBuilder string_2, UIntPtr size);
        int FileInitialize(out IntPtr file, IntPtr error);
        int FileFree(out IntPtr file, IntPtr error);
        int FileSignalAbort(IntPtr file, IntPtr error);
        int FileOpen(IntPtr file, [MarshalAs(UnmanagedType.LPStr)] string filename, int access_flags, IntPtr error);
        int FileOpenWide(IntPtr file, [MarshalAs(UnmanagedType.LPWStr)] string filename, int access_flags, IntPtr error);
        int FileOpenFileIoHandle(IntPtr file, IntPtr file_io_handle, int access_flags, IntPtr error);
        int FileClose(IntPtr file, IntPtr error);
        int FileIsCorrupted(IntPtr file, IntPtr error);
        int FileRecoverItems(IntPtr file, byte recovery_flags, IntPtr error);
        int FileGetSize(IntPtr file, out long size, IntPtr error);
        int FileGetContentType(IntPtr file, out byte content_type, IntPtr error);
        int FileGetType(IntPtr file, out byte type, IntPtr error);
        int FileGetEncryptionType(IntPtr file, out byte encryption_type, IntPtr error);
        int FileGetAsciiCodepage(IntPtr file, out int ascii_codepage, IntPtr error);
        int FileSetAsciiCodepage(IntPtr file, int ascii_codepage, IntPtr error);
        int FileGetNumberOfUnallocatedBlocks(IntPtr file, int unallocated_block_type, out int number_of_unallocated_blocks, IntPtr error);
        int FileGetUnallocatedBlock(IntPtr file, int unallocated_block_type, int unallocated_block_index, out long offset, out long size, IntPtr error);
        int FileGetRootItem(IntPtr file, out IntPtr root_item, IntPtr error);
        int FileGetMessageStore(IntPtr file, out IntPtr message_store, IntPtr error);
        int FileGetNameToIdMap(IntPtr file, out IntPtr name_to_id_map, IntPtr error);
        int FileGetRootFolder(IntPtr file, out IntPtr root_folder, IntPtr error);
        int FileGetItemByIdentifier(IntPtr file, uint item_identifier, out IntPtr item, IntPtr error);
        int FileGetNumberOfOrphanItems(IntPtr file, out int number_of_orphan_items, IntPtr error);
        int FileGetOrphanItemByIndex(IntPtr file, int orphan_item_index, out IntPtr orphan_item, IntPtr error);
        int FileGetNumberOfRecoveredItems(IntPtr file, out int number_of_recovered_items, IntPtr error);
        int FileGetRecoveredItemByIndex(IntPtr file, int recovered_item_index, out IntPtr recovered_item, IntPtr error);
        int FolderGetType(IntPtr folder, out byte type, IntPtr error);
        int FolderGetUtf8NameSize(IntPtr folder, out UIntPtr utf8_string_size, IntPtr error);
        int FolderGetUtf8Name(IntPtr folder, byte[] utf8_string, UIntPtr utf8_string_size, IntPtr error);
        int FolderGetUtf16NameSize(IntPtr folder, out UIntPtr utf16_string_size, IntPtr error);
        int FolderGetUtf16Name(IntPtr folder, ushort[] utf16_string, UIntPtr utf16_string_size, IntPtr error);
        int FolderGetNumberOfSubFolders(IntPtr folder, out int number_of_sub_folders, IntPtr error);
        int FolderGetSubFolder(IntPtr folder, int sub_folder_index, out IntPtr sub_folder, IntPtr error);
        int FolderGetSubFolderByUtf8Name(IntPtr folder, byte[] utf8_sub_folder_name, UIntPtr utf8_sub_folder_name_size, out IntPtr sub_folder, IntPtr error);
        int FolderGetSubFolderByUtf16Name(IntPtr folder, ushort[] utf16_sub_folder_name, UIntPtr utf16_sub_folder_name_size, out IntPtr sub_folder, IntPtr error);
        int FolderGetSubFolders(IntPtr item, out IntPtr sub_folders, IntPtr error);
        int FolderGetNumberOfSubMessages(IntPtr folder, out int number_of_sub_messages, IntPtr error);
        int FolderGetSubMessage(IntPtr folder, int sub_message_index, out IntPtr sub_message, IntPtr error);
        int FolderGetSubMessageByUtf8Name(IntPtr folder, byte[] utf8_sub_message_name, UIntPtr utf8_sub_message_name_size, out IntPtr sub_message, IntPtr error);
        int FolderGetSubMessageByUtf16Name(IntPtr folder, ushort[] utf16_sub_message_name, UIntPtr utf16_sub_message_name_size, out IntPtr sub_message, IntPtr error);
        int FolderGetSubMessages(IntPtr item, out IntPtr sub_messages, IntPtr error);
        int FolderGetNumberOfSubAssociatedContents(IntPtr folder, out int number_of_sub_associated_contents, IntPtr error);
        int FolderGetSubAssociatedContent(IntPtr folder, int sub_associated_content_index, out IntPtr sub_associated_content, IntPtr error);
        int FolderGetSubAssociatedContents(IntPtr item, out IntPtr sub_associated_contents, IntPtr error);
        int FolderGetUnknowns(IntPtr folder, out IntPtr unknowns, IntPtr error);
        int ItemFree(out IntPtr item, IntPtr error);
        int ItemGetIdentifier(IntPtr item, out uint identifier, IntPtr error);
        int ItemGetNumberOfRecordSets(IntPtr item, out int number_of_record_sets, IntPtr error);
        int ItemGetRecordSetByIndex(IntPtr item, int record_set_index, out IntPtr record_set, IntPtr error);
        int ItemGetNumberOfEntries(IntPtr item, out uint number_of_entries, IntPtr error);
        int ItemGetType(IntPtr item, out byte item_type, IntPtr error);
        int ItemGetNumberOfSubItems(IntPtr item, out int number_of_sub_items, IntPtr error);
        int ItemGetSubItem(IntPtr item, int sub_item_index, out IntPtr sub_item, IntPtr error);
        int ItemGetSubItemByIdentifier(IntPtr item, uint sub_item_identifier, out IntPtr sub_item, IntPtr error);
        int FileGetOrphanItem(IntPtr file, int orphan_item_index, out IntPtr orphan_item, IntPtr error);
        int FileGetRecoveredItem(IntPtr file, int recovered_item_index, out IntPtr recovered_item, IntPtr error);
        int ItemClone(out IntPtr destination_item, IntPtr source_item, IntPtr error);
        int ItemGetNumberOfSets(IntPtr item, out uint number_of_sets, IntPtr error);
        int ItemGetEntryType(IntPtr item, int set_index, int entry_index, out uint entry_type, out uint value_type, out IntPtr name_to_id_map_entry, IntPtr error);
        int ItemGetValueType(IntPtr item, int set_index, uint entry_type, out uint value_type, byte flags, IntPtr error);
        int ItemGetEntryValue(IntPtr item, int set_index, uint entry_type, out uint value_type, out IntPtr value_data, out UIntPtr value_data_size, byte flags, IntPtr error);
        int ItemGetEntryValueByUtf8Name(IntPtr item, int set_index, byte[] utf8_entry_name, UIntPtr utf8_entry_name_length, out uint value_type, out IntPtr value_data, out UIntPtr value_data_size, IntPtr error);
        int ItemGetEntryValueByUtf16Name(IntPtr item, int set_index, ushort[] utf16_entry_name, UIntPtr utf16_entry_name_length, out uint value_type, out IntPtr value_data, out UIntPtr value_data_size, IntPtr error);
        int ItemGetEntryValueBoolean(IntPtr item, int set_index, uint entry_type, out byte entry_value, byte flags, IntPtr error);
        int ItemGetEntryValueBooleanByUtf8Name(IntPtr item, int set_index, byte[] utf8_entry_name, UIntPtr utf8_entry_name_length, out byte entry_value, IntPtr error);
        int ItemGetEntryValueBooleanByUtf16Name(IntPtr item, int set_index, ushort[] utf16_entry_name, UIntPtr utf16_entry_name_length, out byte entry_value, IntPtr error);
        int ItemGetEntryValue16bit(IntPtr item, int set_index, uint entry_type, out ushort entry_value, byte flags, IntPtr error);
        int ItemGetEntryValue16bitByUtf8Name(IntPtr item, int set_index, byte[] utf8_entry_name, UIntPtr utf8_entry_name_length, out ushort entry_value, IntPtr error);
        int ItemGetEntryValue16bitByUtf16Name(IntPtr item, int set_index, ushort[] utf16_entry_name, UIntPtr utf16_entry_name_length, out ushort entry_value, IntPtr error);
        int ItemGetEntryValue32bit(IntPtr item, int set_index, uint entry_type, out uint entry_value, byte flags, IntPtr error);
        int ItemGetEntryValue32bitByUtf8Name(IntPtr item, int set_index, byte[] utf8_entry_name, UIntPtr utf8_entry_name_length, out uint entry_value, IntPtr error);
        int ItemGetEntryValue32bitByUtf16Name(IntPtr item, int set_index, ushort[] utf16_entry_name, UIntPtr utf16_entry_name_length, out uint entry_value, IntPtr error);
        int ItemGetEntryValue64bit(IntPtr item, int set_index, uint entry_type, out ulong entry_value, byte flags, IntPtr error);
        int ItemGetEntryValue64bitByUtf8Name(IntPtr item, int set_index, byte[] utf8_entry_name, UIntPtr utf8_entry_name_length, out ulong entry_value, IntPtr error);
        int ItemGetEntryValue64bitByUtf16Name(IntPtr item, int set_index, ushort[] utf16_entry_name, UIntPtr utf16_entry_name_length, out ulong entry_value, IntPtr error);
        int ItemGetEntryValueFiletime(IntPtr item, int set_index, uint entry_type, out ulong entry_value, byte flags, IntPtr error);
        int ItemGetEntryValueFiletimeByUtf8Name(IntPtr item, int set_index, byte[] utf8_entry_name, UIntPtr utf8_entry_name_length, out ulong entry_value, IntPtr error);
        int ItemGetEntryValueFiletimeByUtf16Name(IntPtr item, int set_index, ushort[] utf16_entry_name, UIntPtr utf16_entry_name_length, out ulong entry_value, IntPtr error);
        int ItemGetEntryValueSize(IntPtr item, int set_index, uint entry_type, out UIntPtr entry_value, byte flags, IntPtr error);
        int ItemGetEntryValueSizeByUtf8Name(IntPtr item, int set_index, byte[] utf8_entry_name, UIntPtr utf8_entry_name_length, out UIntPtr entry_value, IntPtr error);
        int ItemGetEntryValueSizeByUtf16Name(IntPtr item, int set_index, ushort[] utf16_entry_name, UIntPtr utf16_entry_name_length, out UIntPtr entry_value, IntPtr error);
        int ItemGetEntryValueFloatingPoint(IntPtr item, int set_index, uint entry_type, out double entry_value, byte flags, IntPtr error);
        int ItemGetEntryValueFloatingPointByUtf8Name(IntPtr item, int set_index, byte[] utf8_entry_name, UIntPtr utf8_entry_name_length, out double entry_value, IntPtr error);
        int ItemGetEntryValueFloatingPointByUtf16Name(IntPtr item, int set_index, ushort[] utf16_entry_name, UIntPtr utf16_entry_name_length, out double entry_value, IntPtr error);
        int ItemGetEntryValueUtf8StringSize(IntPtr item, int set_index, uint entry_type, out UIntPtr utf8_string_size, byte flags, IntPtr error);
        int ItemGetEntryValueUtf8StringSizeByUtf8Name(IntPtr item, int set_index, byte[] utf8_entry_name, UIntPtr utf8_entry_name_length, out UIntPtr utf8_string_size, IntPtr error);
        int ItemGetEntryValueUtf8StringSizeByUtf16Name(IntPtr item, int set_index, ushort[] utf16_entry_name, UIntPtr utf16_entry_name_length, out UIntPtr utf8_string_size, IntPtr error);
        int ItemGetEntryValueUtf8String(IntPtr item, int set_index, uint entry_type, byte[] utf8_string, UIntPtr utf8_string_size, byte flags, IntPtr error);
        int ItemGetEntryValueUtf8StringByUtf8Name(IntPtr item, int set_index, byte[] utf8_entry_name, UIntPtr utf8_entry_name_length, byte[] utf8_string, UIntPtr utf8_string_size, IntPtr error);
        int ItemGetEntryValueUtf8StringByUtf16Name(IntPtr item, int set_index, ushort[] utf16_entry_name, UIntPtr utf16_entry_name_length, byte[] utf8_string, UIntPtr utf8_string_size, IntPtr error);
        int ItemGetEntryValueUtf16StringSize(IntPtr item, int set_index, uint entry_type, out UIntPtr utf16_string_size, byte flags, IntPtr error);
        int ItemGetEntryValueUtf16StringSizeByUtf8Name(IntPtr item, int set_index, byte[] utf8_entry_name, UIntPtr utf8_entry_name_length, out UIntPtr utf16_string_size, IntPtr error);
        int ItemGetEntryValueUtf16StringSizeByUtf16Name(IntPtr item, int set_index, ushort[] utf16_entry_name, UIntPtr utf16_entry_name_length, out UIntPtr utf16_string_size, IntPtr error);
        int ItemGetEntryValueUtf16String(IntPtr item, int set_index, uint entry_type, ushort[] utf16_string, UIntPtr utf16_string_size, byte flags, IntPtr error);
        int ItemGetEntryValueUtf16StringByUtf8Name(IntPtr item, int set_index, byte[] utf8_entry_name, UIntPtr utf8_entry_name_length, ushort[] utf16_string, UIntPtr utf16_string_size, IntPtr error);
        int ItemGetEntryValueUtf16StringByUtf16Name(IntPtr item, int set_index, ushort[] utf16_entry_name, UIntPtr utf16_entry_name_length, ushort[] utf16_string, UIntPtr utf16_string_size, IntPtr error);
        int ItemGetEntryValueBinaryDataSize(IntPtr item, int set_index, uint entry_type, out UIntPtr binary_data_size, byte flags, IntPtr error);
        int ItemGetEntryValueBinaryDataSizeByUtf8Name(IntPtr item, int set_index, byte[] utf8_entry_name, UIntPtr utf8_entry_name_length, out UIntPtr binary_data_size, IntPtr error);
        int ItemGetEntryValueBinaryDataSizeByUtf16Name(IntPtr item, int set_index, ushort[] utf16_entry_name, UIntPtr utf16_entry_name_length, out UIntPtr binary_data_size, IntPtr error);
        int ItemGetEntryValueBinaryData(IntPtr item, int set_index, uint entry_type, byte[] binary_data, UIntPtr binary_data_size, byte flags, IntPtr error);
        int ItemGetEntryValueBinaryDataByUtf8Name(IntPtr item, int set_index, byte[] utf8_entry_name, UIntPtr utf8_entry_name_length, byte[] binary_data, UIntPtr binary_data_size, IntPtr error);
        int ItemGetEntryValueBinaryDataByUtf16Name(IntPtr item, int set_index, ushort[] utf16_entry_name, UIntPtr utf16_entry_name_length, byte[] binary_data, UIntPtr binary_data_size, IntPtr error);
        int ItemGetEntryValueGuid(IntPtr item, int set_index, uint entry_type, byte[] guid, UIntPtr guid_size, byte flags, IntPtr error);
        int ItemGetEntryMultiValue(IntPtr item, int set_index, uint entry_type, out IntPtr multi_value, byte flags, IntPtr error);
        int RecordEntryGetValueDataSize(IntPtr record_entry, out UIntPtr value_data_size, IntPtr error);
        int RecordEntryCopyValueData(IntPtr record_entry, byte[] value_data, UIntPtr value_data_size, IntPtr error);
        int RecordEntryGetValueBoolean(IntPtr record_entry, out byte value_boolean, IntPtr error);
        int RecordEntryGetValue16bit(IntPtr record_entry, out ushort value_16bit, IntPtr error);
        int RecordEntryGetValue32bit(IntPtr record_entry, out uint value_32bit, IntPtr error);
        int RecordEntryGetValue64bit(IntPtr record_entry, out ulong value_64bit, IntPtr error);
        int RecordEntryGetValueFiletime(IntPtr record_entry, out ulong value_64bit, IntPtr error);
        int RecordEntryGetValueSize(IntPtr record_entry, out UIntPtr value_size, IntPtr error);
        int RecordEntryGetValueFloatingPoint(IntPtr record_entry, out double value_floating_point, IntPtr error);
        int RecordEntryGetValueUtf8StringSize(IntPtr record_entry, out UIntPtr utf8_string_size, IntPtr error);
        int RecordEntryGetValueUtf8String(IntPtr record_entry, byte[] utf8_string, UIntPtr utf8_string_size, IntPtr error);
        int RecordEntryGetValueUtf16StringSize(IntPtr record_entry, out UIntPtr utf16_string_size, IntPtr error);
        int RecordEntryGetValueUtf16String(IntPtr record_entry, ushort[] utf16_string, UIntPtr utf16_string_size, IntPtr error);
        int MessageGetEntryValueUtf8StringSize(IntPtr message, uint entry_type, out UIntPtr utf8_string_size, IntPtr error);
        int MessageGetEntryValueUtf8String(IntPtr message, uint entry_type, byte[] utf8_string, UIntPtr utf8_string_size, IntPtr error);
        int MessageGetEntryValueUtf16StringSize(IntPtr message, uint entry_type, out UIntPtr utf16_string_size, IntPtr error);
        int MessageGetEntryValueUtf16String(IntPtr message, uint entry_type, ushort[] utf16_string, UIntPtr utf16_string_size, IntPtr error);
        int MessageGetClientSubmitTime(IntPtr message, out ulong filetime, IntPtr error);
        int MessageGetDeliveryTime(IntPtr message, out ulong filetime, IntPtr error);
        int MessageGetCreationTime(IntPtr message, out ulong filetime, IntPtr error);
        int MessageGetModificationTime(IntPtr message, out ulong filetime, IntPtr error);
        int MessageGetNumberOfAttachments(IntPtr message, out int number_of_attachments, IntPtr error);
        int MessageGetAttachment(IntPtr message, int attachment_index, out IntPtr attachment, IntPtr error);
        int MessageGetAttachments(IntPtr message, out IntPtr attachments, IntPtr error);
        int MessageGetRecipients(IntPtr message, out IntPtr recipients, IntPtr error);
        int MessageGetPlainTextBodySize(IntPtr message, out UIntPtr size, IntPtr error);
        int MessageGetPlainTextBody(IntPtr message, byte[] message_body, UIntPtr size, IntPtr error);
        int MessageGetRtfBodySize(IntPtr message, out UIntPtr size, IntPtr error);
        int MessageGetRtfBody(IntPtr message, byte[] message_body, UIntPtr size, IntPtr error);
        int MessageGetHtmlBodySize(IntPtr message, out UIntPtr size, IntPtr error);
        int MessageGetHtmlBody(IntPtr message, byte[] message_body, UIntPtr size, IntPtr error);
        int MultiValueFree(out IntPtr multi_value, IntPtr error);
        int MultiValueGetNumberOfValues(IntPtr multi_value, out int number_of_values, IntPtr error);
        int MultiValueGetValue(IntPtr multi_value, int value_index, out uint value_type, out IntPtr value_data, out UIntPtr value_data_size, IntPtr error);
        int MultiValueGetValue32bit(IntPtr multi_value, int value_index, out uint value, IntPtr error);
        int MultiValueGetValue64bit(IntPtr multi_value, int value_index, out ulong value, IntPtr error);
        int MultiValueGetValueFiletime(IntPtr multi_value, int value_index, out ulong filetime, IntPtr error);
        int MultiValueGetValueUtf8StringSize(IntPtr multi_value, int value_index, out UIntPtr utf8_string_size, IntPtr error);
        int MultiValueGetValueUtf8String(IntPtr multi_value, int value_index, byte[] utf8_string, UIntPtr utf8_string_size, IntPtr error);
        int MultiValueGetValueUtf16StringSize(IntPtr multi_value, int value_index, out UIntPtr utf16_string_size, IntPtr error);
        int MultiValueGetValueUtf16String(IntPtr multi_value, int value_index, ushort[] utf16_string, UIntPtr utf16_string_size, IntPtr error);
        int MultiValueGetValueBinaryDataSize(IntPtr multi_value, int value_index, out UIntPtr size, IntPtr error);
        int MultiValueGetValueBinaryData(IntPtr multi_value, int value_index, byte[] binary_data, UIntPtr size, IntPtr error);
        int MultiValueGetValueGuid(IntPtr multi_value, int value_index, byte[] guid, UIntPtr size, IntPtr error);
        int NameToIdMapEntryGetType(IntPtr name_to_id_map_entry, out byte entry_type, IntPtr error);
        int NameToIdMapEntryGetNumber(IntPtr name_to_id_map_entry, out uint number, IntPtr error);
        int NameToIdMapEntryGetUtf8StringSize(IntPtr name_to_id_map_entry, out UIntPtr utf8_string_size, IntPtr error);
        int NameToIdMapEntryGetUtf8String(IntPtr name_to_id_map_entry, byte[] utf8_string, UIntPtr utf8_string_size, IntPtr error);
        int NameToIdMapEntryGetUtf16StringSize(IntPtr name_to_id_map_entry, out UIntPtr utf16_string_size, IntPtr error);
        int NameToIdMapEntryGetUtf16String(IntPtr name_to_id_map_entry, ushort[] utf16_string, UIntPtr utf16_string_size, IntPtr error);
        int NameToIdMapEntryGetGuid(IntPtr name_to_id_map_entry, byte[] guid, UIntPtr size, IntPtr error);
        void NotifySetVerbose(int verbose);
        int NotifySetStream(IntPtr stream, IntPtr error);
        int NotifyStreamOpen([MarshalAs(UnmanagedType.LPStr)] string filename, IntPtr error);
        int NotifyStreamClose(IntPtr error);
        int RecordEntryFree(out IntPtr record_entry, IntPtr error);
        int RecordEntryGetEntryType(IntPtr record_entry, out uint entry_type, IntPtr error);
        int RecordEntryGetValueType(IntPtr record_entry, out uint value_type, IntPtr error);
        int RecordEntryGetNameToIdMapEntry(IntPtr record_entry, out IntPtr name_to_id_map_entry, IntPtr error);
        int RecordEntryGetDataSize(IntPtr record_entry, out UIntPtr data_size, IntPtr error);
        int RecordEntryGetData(IntPtr record_entry, byte[] data, UIntPtr data_size, IntPtr error);
        int RecordEntryGetDataAsBoolean(IntPtr record_entry, out byte value_boolean, IntPtr error);
        int RecordEntryGetDataAs16bitInteger(IntPtr record_entry, out ushort value_16bit, IntPtr error);
        int RecordEntryGetDataAs32bitInteger(IntPtr record_entry, out uint value_32bit, IntPtr error);
        int RecordEntryGetDataAs64bitInteger(IntPtr record_entry, out ulong value_64bit, IntPtr error);
        int RecordEntryGetDataAsFiletime(IntPtr record_entry, out ulong filetime, IntPtr error);
        int RecordEntryGetDataAsFloatingtime(IntPtr record_entry, out ulong floatingtime, IntPtr error);
        int RecordEntryGetDataAsSize(IntPtr record_entry, out long value_size, IntPtr error);
        int RecordEntryGetDataAsFloatingPoint(IntPtr record_entry, out double value_floating_point, IntPtr error);
        int RecordEntryGetDataAsUtf8StringSize(IntPtr record_entry, out UIntPtr utf8_string_size, IntPtr error);
        int RecordEntryGetDataAsUtf8String(IntPtr record_entry, byte[] utf8_string, UIntPtr utf8_string_size, IntPtr error);
        int RecordEntryGetDataAsUtf16StringSize(IntPtr record_entry, out UIntPtr utf16_string_size, IntPtr error);
        int RecordEntryGetDataAsUtf16String(IntPtr record_entry, ushort[] utf16_string, UIntPtr utf16_string_size, IntPtr error);
        int RecordEntryGetDataAsGuid(IntPtr record_entry, byte[] gui_data, UIntPtr guid_data_size, IntPtr error);
        int RecordEntryGetMultiValue(IntPtr record_entry, out IntPtr multi_value, IntPtr error);
        long RecordEntryReadBuffer(IntPtr record_entry, byte[] buffer, UIntPtr buffer_size, IntPtr error);
        long RecordEntrySeekOffset(IntPtr record_entry, long offset, int whence, IntPtr error);
        int RecordSetFree(out IntPtr record_set, IntPtr error);
        int RecordSetGetNumberOfEntries(IntPtr record_set, out int number_of_entries, IntPtr error);
        int RecordSetGetEntryByIndex(IntPtr record_set, int entry_index, out IntPtr record_entry, IntPtr error);
        int RecordSetGetEntryByType(IntPtr record_set, uint entry_type, uint value_type, out IntPtr record_entry, byte flags, IntPtr error);
        int RecordSetGetEntryByUtf8Name(IntPtr record_set, byte[] utf8_string, UIntPtr utf8_string_length, uint value_type, out IntPtr record_entry, byte flags, IntPtr error);
        int RecordSetGetEntryByUtf16Name(IntPtr record_set, ushort[] utf16_string, UIntPtr utf16_string_length, uint value_type, out IntPtr record_entry, byte flags, IntPtr error);
        int GetAccessFlagsRead();
        int GetCodepage(out int codepage, IntPtr error);
        int SetCodepage(int codepage, IntPtr error);
        int CheckFileSignature([MarshalAs(UnmanagedType.LPStr)] string filename, IntPtr error);
        int CheckFileSignatureWide([MarshalAs(UnmanagedType.LPWStr)] string filename, IntPtr error);
        int CheckFileSignatureFileIoHandle(IntPtr file_io_handle, IntPtr error);
    }
}